### ISSUE TITLE
  no applicable method for 'accuracy' applied to an object of class "forecast"

### ISSUE THREAD

**Issue by Uday-461** [AbhishekBanerjee499/Microsoft_stock_prediction_R#1]
> # ARIMA model
> fit_arima <- auto.arima(train$Close_new)
> fcast_arima <- forecast(fit_arima, h = nrow(test))
> accuracy(fcast_arima, test$Close_new)
Error in UseMethod("accuracy") : 
  no applicable method for 'accuracy' applied to an object of class "forecast"

**Comment by AbhishekBanerjee499** [comment]
This error indicates that 'accuracy' function is not compatible with the 'forecast' object generated by the 'forecast' function in your code. To resolve this issue, you need to make sure you are using the correct 'accuracy' function that corresponds to the type of model you are using. For ARIMA model, you should use the 'accuracy' function from the 'forecast' package, not the one from the 'stats' package. So make sure library forecast is installed and called while running the code. I'm also attaching versions of libraries and R as used.
R studio: 1.1.456
R: 4.2.1
ggplot: 3.4.2
forecast: 8.21
tseries: 0.10-54
rugarch: 1.4-9
rpart: 4.1.16


Hope this helps @Uday-461
